use_frameworks!

platform :ios, '9.0'

target 'HHKeyboard_Example' do
  pod 'HHKeyboard', :path => '../'
  pod 'HHKeyboard/Face', :path => '../'

  target 'HHKeyboard_Tests' do
    inherit! :search_paths

    
  end
end
